global:
  scrape_interval: 15s

# rule_files:
#   - "/etc/prometheus/unklab_node_exporter.yml"

scrape_configs:
  - job_name: "animemoeus_mono_backend"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["api.animemoe.us"]
  - job_name: "unklab_node_exporter"
    static_configs:
      - targets: ["node-exporter.unklab.id"]
