global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/unklab_node_exporter.yml"
#   - "/etc/prometheus/targets2.yml"

scrape_configs:
  - job_name: "animemoeus_mono_backend"
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ["api.animemoe.us"]
